import { Button } from "@/components/ui/button";
import { IBM_Plex_Serif } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { any, string, z } from "zod";
import Nav from "~/components/Nav";
import { useFormStore } from "~/state/stateForm";
import { api } from "~/utils/api";
import type { AllTypes } from "~/server/api/routers/example";

const ibm_serif = IBM_Plex_Serif({
  weight: '700',
  subsets: ['latin']
}) 

export default function Home() {
  const hello = api.example.hello.useQuery(
    ( useFormStore.getState() as z.infer<typeof AllTypes> ) );
  console.log(hello.data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between">
        <Nav logoFont={ibm_serif.className} />
        <div className="container h-screen flex flex-col items-center gap-6 px-4 py-10 ">
          <h1 className={ibm_serif.className + " text-3xl sm:text-5xl text-slate-800"}>
            Twoj asystent w wyborze ścieżki życia
          </h1>
          <p className="text-lg">
            Rozwiąż nasz quiz i dowiedz się, która uczelnia jest dla Ciebie idealna!
            Zajmie Ci to tylko 5 minut!
          </p>
         
          <div className="flex items-center justify-around w-full">
            {/* <ArrowDownIcon className="w-10 h-10" /> */}
            <p className="text-lg">Zobacz jakie to <span className="font-bold underline underline-offset-4">proste</span></p>

            
            <Button className="p-6 px-10" >
              <p className="text-lg">Rozpocznij quiz</p>
            </Button>
          </div>
           <Image src="/spektrum.png" className=" border-2 border-black " width={500} height={500} alt="logo" />

          <p className="text-2xl">
            {/* {hello.data ? hello.data : "Loading tRPC query..."} */}
          </p>
        </div>
      </main>
    </>
  );
}
